# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 793f07e692d512aa847fa4e5e5a921ac0ebf4819b5e8d06a06482f36e85202e1877a42d3de0288e511c30c87519553178199aa2983b9fec1cd32ef74c97c5fde

test:
  secret_key_base: 3b5f0c05b530032a31f5f0f42e16751711d211b385c5491da38cfa0dee6a4bddf974c7aec49909b47280385730a6c9e69dde9072aa3f75c0cac320b0cc034405

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
